name: Update events

on:
  schedule:
    - cron: "0 6 */2 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python deps
        run: |
          pip install -r scraper/requirements.txt

      - name: Install Playwright
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python scraper/scrape.py

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/events.json
          git diff --cached --quiet || (git commit -m "Update events" && git push)
